name: Terraform Destroy

on:

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:

  destroy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Configure AWS Credentials

      uses: aws-actions/configure-aws-credentials@v4

      with:
        role-to-assume: arn:aws:iam::940827433372:role/GitHubActionsRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform

      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init

      run: terraform init

    - name: Terraform Destroy

      run: terraform destroy -auto-approve
